# This file describes the serverless stack that serves as the back-end for the Litter Map application.
#
# Quick reference links:
#
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
# https://theburningmonk.com/cloudformation-ref-and-getatt-cheatsheet/

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Global location submission and retrieval system

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs14.x
    CodeUri: functions

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      Name: littermap-api
      Description: REST API for the Litter Map backend
      StageName: !Ref DeploymentStage
      OpenApiVersion: 3.0.3
      Auth:
        Authorizers: []

  CommonLib:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lib-common
      ContentUri: lib/common
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

  PostgresLib:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lib-postgres
      ContentUri: lib/postgres
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

  LogEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: log-event
      Description: Record a single event in the event log table
      Role: !GetAtt LogEventFunctionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref EventsTable
    Metadata:
      BuildMethod: makefile

  AddLocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: add-location
      Description: Add a location
      Role: !GetAtt AddLocationFunctionRole.Arn
      Layers:
        - !Ref CommonLib
        - !Ref PostgresLib
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref SessionsTable
          SESSION_LIFETIME_IN_DAYS: !Ref SessionLifetimeInDays
          PGHOST: !GetAtt MainDB.Endpoint.Address
          PGPORT: !GetAtt MainDB.Endpoint.Port
          PGDATABASE: !Ref DBName
          PGUSER: writer
          PGPASSWORD: !Ref DBWriterPassword
      Events:
        AddLocation:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /add
            Method: POST
    Metadata:
      BuildMethod: makefile

  GetLocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-location
      Description: Retrieve a location by its id
      Role: !GetAtt DBAccessFunctionRole.Arn
      Layers:
        - !Ref CommonLib
        - !Ref PostgresLib
      Environment:
        Variables:
          PGHOST: !GetAtt MainDB.Endpoint.Address
          PGPORT: !GetAtt MainDB.Endpoint.Port
          PGDATABASE: !Ref DBName
          PGUSER: reader
          PGPASSWORD: !Ref DBReaderPassword
      Events:
        GetLocationById:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /id/{id}
            Method: GET
            RequestParameters:
              - method.request.path.id:
                  Required: true
                  Caching: false
        GetLocationsByRadius:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /radius
            Method: GET
            RequestParameters:
              - method.request.querystring.lat:
                  Required: true
                  Caching: false
              - method.request.querystring.lon:
                  Required: true
                  Caching: false
              - method.request.querystring.r:
                  Required: true
                  Caching: false
              - method.request.querystring.format:
                  Required: false
                  Caching: false
    Metadata:
      BuildMethod: makefile

  InfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: info
      Description: Look up privileged information
      Role: !GetAtt InfoFunctionRole.Arn
      Layers:
        - !Ref CommonLib
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref SessionsTable
          SESSION_LIFETIME_IN_DAYS: !Ref SessionLifetimeInDays
          USERS_TABLE: !Ref UsersTable
      Events:
        GetProfileInfo:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /profile
            Method: GET
    Metadata:
      BuildMethod: makefile

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: login
      Description: Login proxy (redirects to third-party sign-in dialog)
      Role: !GetAtt LoginFunctionRole.Arn
      Layers:
        - !Ref CommonLib
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref SessionsTable
          SESSION_LIFETIME_IN_DAYS: !Ref SessionLifetimeInDays
          CLIENTID_GOOGLE: !Ref GoogleClientId
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /login/{service}
            Method: GET
            RequestParameters:
              - method.request.path.service:
                  Required: true
                  Caching: false
        Logout:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /logout
            Method: GET
    Metadata:
      BuildMethod: makefile

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: auth
      Description: Receive authorization from third-party sign-in dialog and start an authenticated user session
      Role: !GetAtt AuthFunctionRole.Arn
      Layers:
        - !Ref CommonLib
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref SessionsTable
          SESSION_LIFETIME_IN_DAYS: !Ref SessionLifetimeInDays
          USERS_TABLE: !Ref UsersTable
          CLIENTID_GOOGLE: !Ref GoogleClientId
          CLIENTSECRET_GOOGLE: !Ref GoogleClientSecret
      Events:
        Authentication:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /auth/{service}
            Method: GET
            RequestParameters:
              - method.request.path.service:
                  Required: true
                  Caching: false
    Metadata:
      BuildMethod: makefile

  DBInitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: db-init
      Description: Administrative lambda that initilizes the littermap-db database
      Role: !GetAtt DBAccessFunctionRole.Arn
      Timeout: 10
      Layers:
        - !Ref PostgresLib
      Environment:
        Variables:
          PGHOST: !GetAtt MainDB.Endpoint.Address
          PGPORT: !GetAtt MainDB.Endpoint.Port
          PGDATABASE: !Ref DBName
          PGUSER: !Ref DBAdminUser
          PGPASSWORD: !Ref DBAdminPassword
          DB_WRITER_PASSWORD: !Ref DBWriterPassword
          DB_READER_PASSWORD: !Ref DBReaderPassword
    Metadata:
      BuildMethod: makefile

  DBRunFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: db-run
      Description: Runs a database query (as administrator)
      Role: !GetAtt DBAccessFunctionRole.Arn
      Layers:
        - !Ref PostgresLib
      Environment:
        Variables:
          PGHOST: !GetAtt MainDB.Endpoint.Address
          PGPORT: !GetAtt MainDB.Endpoint.Port
          PGDATABASE: !Ref DBName
          DB_ADMIN: !Ref DBAdminUser
          DB_ADMIN_PASSWORD: !Ref DBAdminPassword
          DB_WRITER_PASSWORD: !Ref DBWriterPassword
          DB_READER_PASSWORD: !Ref DBReaderPassword
    Metadata:
      BuildMethod: makefile

  AddLocationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
            Action:
              - sts:AssumeRole


  InfoFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  LoginFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  AuthFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  LogEventFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: eventlog-write
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: dynamodb:PutItem
                Resource: !GetAtt EventsTable.Arn
                Effect: Allow

  DBAccessFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  AllowDBAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: allow-rds-connect
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: rds-db:connect
            Resource: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${MainDB}
            Effect: Allow
      Roles:
        - Ref: DBAccessFunctionRole
        - Ref: AddLocationFunctionRole

  AllowUsersAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: allow-users-access
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            Resource: !GetAtt UsersTable.Arn
            Effect: Allow
      Roles:
        - Ref: InfoFunctionRole
        - Ref: AuthFunctionRole

  AllowSessionsAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: allow-sessions-access
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            Resource: !GetAtt SessionsTable.Arn
            Effect: Allow
      Roles:
        - Ref: InfoFunctionRole
        - Ref: LoginFunctionRole
        - Ref: AuthFunctionRole
        - Ref: AddLocationFunctionRole

  AllowLogEventPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: allow-log-event
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: lambda:InvokeFunction
            Resource: !GetAtt LogEventFunction.Arn
            Effect: Allow
      Roles:
        - Ref: LoginFunctionRole
        - Ref: AuthFunctionRole
        - Ref: AddLocationFunctionRole

  # Main database that stores the world
  MainDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBName
      DBSnapshotIdentifier: !If [HasDBSnapshotIdentifier, !Ref DBSnapshotIdentifier, !Ref 'AWS::NoValue']
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: !Ref DBPostgresVersion
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      BackupRetentionPeriod: 0 # no automated backups
      MasterUsername: !Ref DBAdminUser
      MasterUserPassword: !Ref DBAdminPassword

  # Users
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref UsersTableReadCapacity
        WriteCapacityUnits: !Ref UsersTableWriteCapacity

  # Sessions
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: sessions
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref SessionsTableReadCapacity
        WriteCapacityUnits: !Ref SessionsTableWriteCapacity

  # Event log
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: event-log
      AttributeDefinitions:
        - AttributeName: date_key
          AttributeType: S
        - AttributeName: time_key
          AttributeType: S
      KeySchema:
        - AttributeName: date_key
          KeyType: HASH
        - AttributeName: time_key
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref EventLogReadCapacity
        WriteCapacityUnits: !Ref EventLogWriteCapacity

Parameters:
  DeploymentStage:
    Description: Deployment stage
    Type: String
    Default: dev
  DBInstanceClass:
    Description: Database instance class
    Type: String
    Default: db.t2.micro
  DBPostgresVersion:
    Description: PostgreSQL version
    Type: String
    Default: 12.7
  DBAllocatedStorage:
    Description: Allocated storage (in GB)
    Type: Number
    Default: 5
  DBSnapshotIdentifier:
    Description: Provide the database snapshot id if you don't want a new database
    Type: String
  DBName:
    Description: Database name
    Type: String
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: littermap
  DBAdminUser:
    Description: Database admin username
    Type: String
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: litteradmin
  DBAdminPassword:
    Description: Database admin password
    Type: String
    MinLength: 8
    MaxLength: 128
    AllowedPattern: "[^\\s@\"\\/]*"
    ConstraintDescription: 'The password must be 8 to 128 characters and can include any printable ASCII character except "/", """, or "@"'
    Default: makeitpristine
  DBWriterPassword:
    Description: Database write access password
    Type: String
    MinLength: 8
    MaxLength: 128
    AllowedPattern: "[^\\s@\"\\/]*"
    ConstraintDescription: 'The password must be 8 to 128 characters and can include any printable ASCII character except "/", """, or "@"'
    Default: recorder
  DBReaderPassword:
    Description: Database reader access password
    Type: String
    MinLength: 8
    MaxLength: 128
    AllowedPattern: "[^\\s@\"\\/]*"
    ConstraintDescription: 'The password must be 8 to 128 characters and can include any printable ASCII character except "/", """, or "@"'
    Default: observer
  GoogleClientId:
    Description: Client ID issued by Google for third-party sign-in authentication
    Type: String
  GoogleClientSecret:
    Description: Client secret issued by Google for third-party sign-in authentication
    Type: String
  UsersTableReadCapacity:
    Description: Users table provisioned read capacity
    Type: Number
    Default: 1
  UsersTableWriteCapacity:
    Description: Users table provisioned write capacity
    Type: Number
    Default: 1
  SessionLifetimeInDays:
    Description: How many days will browser sessions expire after they were created
    Type: Number
    Default: 3
  SessionsTableReadCapacity:
    Description: Session table provisioned read capacity
    Type: Number
    Default: 1
  SessionsTableWriteCapacity:
    Description: Session table provisioned write capacity
    Type: Number
    Default: 1
  EventLogReadCapacity:
    Description: Event log table provisioned read capacity
    Type: Number
    Default: 1
  EventLogWriteCapacity:
    Description: Event log table provisioned write capacity
    Type: Number
    Default: 1

Conditions:
  HasNotDBSnapshotIdentifier: !Equals [!Ref DBSnapshotIdentifier, '']
  HasDBSnapshotIdentifier: !Not [!Condition HasNotDBSnapshotIdentifier]

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Database Configuration"
        Parameters:
          - DBInstanceClass
          - DBPostgresVersion
          - DBAllocatedStorage
          - DBSnapshotIdentifier
          - DBAdminUser
          - DBAdminPassword
          - DBWriterPassword
          - DBReaderPassword

Outputs:
  MainDBHost:
    Description: Database remote host
    Value: !Sub "postgresql://${MainDB.Endpoint.Address}:${MainDB.Endpoint.Port}/${DBName}"
  API:
    Description: Endpoint URL
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${API.Stage}/"
  Application:
    Description: Manage this application
    Value: !Sub "https://console.aws.amazon.com/lambda/home?region=${AWS::Region}#/applications/${AWS::StackName}"
